version: "3.8"
services:
  postgres-phonebook:
    image: postgres:latest
    restart: always
    container_name: postgres-phonebook
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db_phonebook
    ports:
      - '5433:5432'
    volumes:
      - db_phonebook:/var/lib/postgresql/data

volumes:
  db_phonebook:
    driver: local